### ISSUE TITLE
write_bfree_blocks function free error

### ISSUE THREAD

**Issue by linuxgcc** [jserv/simplefs#19]
file : mkfs.c 
fucntion:  write_bfree_blocks
line : bfree[i] = htole64(line)
block arr  is out of bounds.

**Comment by jserv** [comment]
Can you please send pull request(s) which would address the above issue?

**Comment by lightmelodies** [comment]
If I understand correctly, the first block can only contain 4096 * 8 bits，which is not enough for larger block device (nr_used > 32768).

**Comment by jserv** [comment]
This task was considered invalid.
