### ISSUE TITLE
inode.c

### ISSUE THREAD

**Issue by cbkadal** [jserv/simplefs#25]
FILE: inode.c

At line 199 and 222:
inode_init_owner(&nop_mnt_idmap, inode, dir, inode->mode);
s/mode/i_mode/

**Comment by jserv** [comment]
Hi @cbkadal,
Can you please send a pull request accordingly?

**Comment by cbkadal** [comment]
My apology for not knowing what/how to "pull request." I will find out how to do that properly. BTW, I tried with kernel version 6.1.32 and 6.3.6, and found that:
* the bit modes are not correct for kernel 6.3.6
* the file count is not correct for both kernels.

```
Linux 6.1.32
total 2
-rw-r--r-- 1 root root  0 Jun  8 10:34 file1.txt
-rw-r--r-- 1 root root 30 Jun  8 10:34 file2.txt
-rw-r--r-- 1 root root  0 Jun  8 10:34 file3.txt

Linux 6.3.6
total 2
?--------- 1 root root  0 Jun  8 10:30 file1.txt
?--------- 1 root root 30 Jun  8 10:30 file2.txt
?--------- 1 root root  0 Jun  8 10:30 file3.txt
```

**Comment by jserv** [comment]
I defer to @fewletter .

**Comment by jserv** [comment]
Close in favor of #27 .
