### ISSUE TITLE
Any plans to make a "book"?

### ISSUE THREAD

**Issue by thefossguy** [jserv/simplefs#41]
I was wandering on your GitHub profile after reading the LKMPG book and found it useful. I see that this is another, similar effort, but for VFS. I'm wondering if you plan on writing some educational material around this. :)

**Comment by Yueh-Wang** [comment]
您好，您的邮件我已收到，我会尽快给您回复。

**Comment by jserv** [comment]
You may consider [Linux filesystem](https://github.com/stevedpate/linux-fs-book), an incomplete book on Linux filesystems from a kernel perspective.
