### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by HotMercury** [jserv/simplefs#50]
If I fill the image with `/dev/random`, the `touch` or `mkdir` command will error.

Reproduce:
```shell
$ dd if=/dev/random of=test.img bs=1M count=32
$ ./mkfs.simplefs test.img
$ mkdir test
$ sudo mount -t simplefs -o loop test.img test
$ cd test
$ touch test.txt
```

The error message comes up, but if I replace `/dev/random` with `/dev/zero, it will work correctly.
The error message:
```
touch: cannot touch 'test.txt': Input/output error
```

**Comment by jserv** [comment]
> If I fill the image with `/dev/random`, command `touch` or `mkdir` will error

Did you run `mkfs.simplefs` before mounting the image file?

**Comment by HotMercury** [comment]
Yes, following is my detail actions
```
$ dd if=/dev/random of=test.img bs=1M count=32
$ ./mkfs.simplefs test.img
$ mkdir test
$ sudo mount -t simplefs -o loop test.img test
$ cd test
[test] $ touch test.txt
```
the error message comes up, but if I replace `/dev/random` with `/dev/zero`, it will work correctly.

**Comment by jserv** [comment]
Close via #51
