### ISSUE TITLE
New mkfs.simplefs version can not format a device (/dev) file.

### ISSUE THREAD

**Issue by cbkadal** [jserv/simplefs#52]
E.g., when "mkfs.simplefs /dev/sdb1"
ERROR: BLKGETSIZE64 Bad address.

**Comment by jserv** [comment]
> E.g., when "mkfs.simplefs /dev/sdb1" ERROR: BLKGETSIZE64 Bad address.

Can you try commit 5e11fa703e47514d828dcb1d599e0ff7d69bd35b ?

**Comment by cbkadal** [comment]
mkfs.simplefs works again.
```
simplefs$ uname -r
6.9.0-241vbox-14

simplefs$ arch
x86_64

simplefs$ sudo ./mkfs.simplefs /dev/sdb1
Superblock: (4096)
	magic=0xdeadce
	nr_blocks=2560
	nr_inodes=2576 (istore=46 blocks)
	nr_ifree_blocks=1
	nr_bfree_blocks=1
	nr_free_inodes=2575
	nr_free_blocks=2511
Inode store: wrote 46 blocks
	inode size = 72 B
Ifree blocks: wrote 1 blocks
Bfree blocks: wrote 1 blocks
```
Will test is later.
Thanks!

**Comment by jserv** [comment]
I defer to @HotMercury for confirmation.

**Comment by HotMercury** [comment]
Hi @cbkadal 
I am able to run `sudo ./mkfs.simplefs /dev/loop9` normally on version 6.8. 
Are you still encountering execution errors?

**Comment by jserv** [comment]
Close as there is no further action.
